// ── NEXUS RESEARCH — REPORT REGISTRY ─────────────────────────────────────────
// This is the single source of truth for all Nexus Research reports.
// Add new reports here. Both nexus.html and recruiters.html read from this file.

const NEXUS_REPORTS = [
  {
    id: "hormuz-2026-06",
    date: "2026-06-08",
    title: "Running on Empty — Strait of Hormuz Duration Shock",
    subtitle: "WATCH Thesis: Energy system is buffer-constrained, not supply-constrained; duration risk dominates pricing",
    company: "N/A",
    ticker: "N/A",
    exchange: "N/A",
    sector: "Energy / Macro / Geopolitics",
    rating: "WATCH",
    type: "Thematic Note",
    format: "Report",
    conviction: "Medium",
    priceTarget: "N/A",
    upside: "N/A",
    link: "https://view.officeapps.live.com/op/view.aspx?src=https://raptor8600.github.io/Portfolio-Site/Memo_Strait_of_Hormuz.docx",
    summary: "The Strait of Hormuz disruption is framed as a supply shock, but the binding constraint is system buffer duration rather than absolute oil availability. While global production can physically offset part of the loss via rerouting (Cape of Good Hope), the system is operating with reduced strategic and commercial buffers, making time the critical variable. Cushing inventories have fallen to ~22.4M barrels and are approaching operational constraints, while SPR levels have been materially drawn down, limiting policy backstop capacity. The market is currently pricing a short-duration disruption (2–3 months), but evidence points to a higher probability of a 2–3 quarter or longer normalization path. Key catalysts include the unresolved diplomatic MOU, weekly EIA inventory dynamics, and seasonal demand peak pressure in July. The asymmetry lies in duration mispricing: a prolonged closure would exhaust hedging layers across airlines and petrochemicals and structurally reprice energy transport costs beyond the immediate price spike.",
    tags: [
      "Energy",
      "Geopolitics",
      "Oil Markets",
      "Macro Liquidity",
      "Supply Chain",
      "Duration Risk",
      "Cushing Inventories",
      "Strategic Petroleum Reserve"
    ]
  },
  {
    id: "ionq-2026-05",
    date: "2026-05-28",
    title: "IonQ, Inc. — Watch",
    subtitle: "Watch Thesis: Vertically integrated platform bet with $89 blended price target against accelerating cash burn",
    company: "IonQ, Inc.",
    ticker: "IONQ",
    exchange: "NYSE",
    sector: "Quantum Computing",
    rating: "WATCH",
    type: "Moonshot Assessment",
    format: "Report",
    conviction: "Medium",
    priceTarget: "$89",
    upside: "+28.4%",
    link: "https://view.officeapps.live.com/op/view.aspx?src=https://raptor8600.github.io/Portfolio-Site/Memo_IonQ_WATCH.docx",
    summary: "The market prices IonQ at 83x NTM revenue, embedding a base case where government backlog converts and a hyperscaler eventually acquires the platform. The real question is whether IonQ's aggressive acquisition spree — eight companies since 2025 including the pending $1.8B SkyWater semiconductor foundry — accelerates the technology roadmap or simply accelerates cash burn. Q1 2026 operating cash outflow hit $151M, up 4.6x year over year, while the $470M government backlog and 23.6-quarter runway provide a credible survival window. The thesis resolves across the next 2 to 4 quarters as SkyWater closes and Q2/Q3 2026 cash flow is reported.",
    tags: [
      "Quantum Computing",
      "Deep Tech",
      "Moonshot",
      "Government Contracts"
    ]
  },
  {
    id: "cost-2026-05",
    date: "2026-05-12",
    title: "Costco Wholesale Corporation — Neutral/Hold",
    subtitle: "HOLD Thesis: Growth drivers maturing with 53x P/E leaving no margin of safety",
    company: "Costco Wholesale Corporation",
    ticker: "COST",
    exchange: "NasdaqGS",
    sector: "Consumer Defensive",
    rating: "HOLD/NEUTRAL",
    type: "Stock Memo / Quick Pitch",
    format: "Report",
    conviction: "Medium",
    priceTarget: "$957",
    upside: "-6.9%",
    link: "https://view.officeapps.live.com/op/view.aspx?src=https://raptor8600.github.io/Portfolio-Site/Memo_Neutral_Hold__HOLD__COST.docx",
    summary: "The market believes Costco can continue compounding earnings at a premium rate because its membership model creates stable recurring revenue, high loyalty, and structural pricing advantages competitors cannot replicate. In reality, Costco’s strongest growth drivers are naturally maturing — domestic warehouse density, renewal rates, and executive penetration are approaching natural ceilings — and the current 53x P/E leaves no margin of safety for even modest growth normalization. This becomes visible across the next 2–4 earnings cycles as membership momentum data is reported.",
    tags: [
      "Consumer Defensive",
      "Retail",
      "Valuation"
    ]
  },
  {
    id: "kvue-2026-05",
    date: "2026-05-11",
    title: "Kenvue Inc. — Directional Thesis",
    subtitle: "BUY Thesis: Volume inflection mispriced at 11x EV/EBITDA vs. 15.3x peers",
    company: "Kenvue Inc.",
    ticker: "KVUE",
    exchange: "NYSE",
    sector: "Consumer Defensive",
    rating: "BUY",
    type: "Stock Memo / Quick Pitch",
    format: "Report",
    conviction: "High",
    priceTarget: "$22.29",
    upside: "+30%",
    link: "https://view.officeapps.live.com/op/view.aspx?src=https://raptor8600.github.io/Portfolio-Site/Memo_KVUE_BUY_Directional_Thesis.docx",
    summary: "The market believes KVUE is dead money until the KMB deal closes — weighed down by chronic volume declines and litigation overhang — because five consecutive quarters of negative volume signal permanent deterioration, not a cyclical blip. This thesis argues the margin driver is being misread: supply chain automation (60% of capex) and portfolio rationalization are expanding margins toward 20%+ by 2030. Q1 2026 already showed the inflection: 80bps sequential volume improvement and 33% adjusted EPS growth on 4.5% revenue. At ~11x EV/EBITDA vs. 15.3x peer average, the stock offers ~30% upside to a blended $22.29 target, anchored by the KMB acquisition deal at $23.00.",
    tags: [
      "Consumer Defensive",
      "M&A Arbitrage",
      "Margin Expansion",
      "Value"
    ]
  },
  {
    id: "dis-2025-02",
    date: "2025-02-17",
    title: "The Walt Disney Company (DIS) — Executive Summary",
    subtitle: "BUY Thesis: Turnaround marked by DTC streaming profitability and ESPN market leadership",
    company: "The Walt Disney Company",
    ticker: "DIS",
    exchange: "NYSE",
    sector: "Communication Services",
    rating: "BUY",
    type: "Stock Memo / Quick Pitch",
    format: "Report",
    conviction: "High",
    priceTarget: "$135.00",
    upside: "+25%",
    link: "https://lnkd.in/gEEi_sSJ",
    summary: "Assessing a strategic turnaround marked by accelerating streaming profitability and segment strength. This executive summary assesses the company as a Strong Buy, highlighting the DTC segment's path to profitability, ESPN's market leadership, and robust Parks growth as key drivers, supported by expanding EBITDA margins and strong cash generation.",
    tags: ["Media", "Streaming", "DTC Profitability", "Turnaround"]
  },
  {
    id: "yum-2025-04",
    date: "2025-04-07",
    title: "Yum! Brands — Digital Transformation & Global Expansion",
    subtitle: "BUY Thesis: 20% drop post-Q3 earnings miss presents compelling value opportunity",
    company: "Yum! Brands Inc.",
    ticker: "YUM",
    exchange: "NYSE",
    sector: "Consumer Discretionary",
    rating: "BUY",
    type: "Stock Memo / Quick Pitch",
    format: "Report",
    conviction: "Medium",
    priceTarget: "$150.00",
    upside: "+20%",
    link: "https://www.linkedin.com/feed/update/urn:li:activity:7313703713284464641/",
    summary: "Evaluating a retail giant's sharp stock decline following a Q3 earnings miss. This analysis argues the 20% drop presents a long-term value opportunity, citing strong brand loyalty, digital sales growth, and private-label expansion as a resilient foundation despite near-term margin pressures and weak discretionary spending.",
    tags: ["Restaurants", "Digital Transformation", "Value"]
  },
  {
    id: "tgt-2024-11",
    date: "2024-11-22",
    title: "Target Corp (TGT) 20% Drop: Opportunity or Red Flag?",
    subtitle: "BUY / Value Thesis: Q3 downturn overdone relative to digital growth and dividend safety",
    company: "Target Corporation",
    ticker: "TGT",
    exchange: "NYSE",
    sector: "Consumer Defensive",
    rating: "BUY",
    type: "Stock Memo / Quick Pitch",
    format: "Article",
    conviction: "Medium",
    priceTarget: "$165.00",
    upside: "+22%",
    link: "https://www.linkedin.com/pulse/targets-tgt-20-drop-value-investors-opportunity-red-flag-mary-scott-ppn4c/",
    summary: "A deep dive into Target's severe Q3 2024 downturn, evaluating whether it signals a terminal risk or a long-term value play. By applying Peter Lynch’s investment principles, this report assesses digital growth prospects, private-label strength, and economic sensitivities to determine the sustainability of its dividend recovery.",
    tags: ["Retail", "Dividend Aristocrat", "Value Investing"]
  },
  {
    id: "tgt-peer-2026-01",
    date: "2026-01-15",
    title: "Retail Earnings Peer Analysis (TGT vs WMT, COST, DG, DLTR)",
    subtitle: "Sector Intelligence & IR Benchmarking across the Big-Box landscape",
    company: "Target Corp & Retail Peers",
    ticker: "TGT",
    exchange: "NYSE",
    sector: "Consumer Defensive",
    rating: "WATCH",
    type: "Deep Dive / Sector Primer",
    format: "Article",
    conviction: "High",
    priceTarget: "N/A",
    upside: "Peer Matrix",
    link: "https://docs.google.com/presentation/d/1cOVJrizNZ8qmOTo5j3m7rSk3Hl5irum1fRXu4-P0jQE/edit?usp=sharing",
    summary: "A comprehensive quarterly earnings analysis of Target Corp (TGT) against core consumer retail peers (Walmart, Costco, Dollar Tree, Dollar General). Synthesizes complex financial KPIs into actionable investor intelligence, valuation multiple cross-referencing, and narrative synthesis for executive decision-making.",
    tags: ["Sector Analysis", "Peer Benchmarking", "IR Strategy", "Retail"]
  },
  {
    id: "ai-bubble-2024-05",
    date: "2024-05-01",
    title: "The AI Bubble: An (Economic) Analysis",
    subtitle: "THESIS CHECK: Speculative capital flows collide with high rates and valuation multiples",
    company: "N/A",
    ticker: "N/A",
    exchange: "N/A",
    sector: "Information Technology",
    rating: "THESIS CHECK",
    type: "Thematic Note",
    format: "Article",
    conviction: "High",
    priceTarget: "N/A",
    upside: "N/A",
    link: "https://www.linkedin.com/pulse/ai-bubble-economic-analysis-how-became-where-we-now-what-mary-scott-tey7c/",
    summary: "An economic critique of the massive capital flows into artificial intelligence, identifying classic speculative bubble characteristics reminiscent of the dot-com era. The analysis forecasts potential market shifts as high interest rates collide with inflated valuations, potentially ushering in a decade of defensive performance.",
    tags: ["Macroeconomics", "AI Bubble", "Market Valuation", "Tech"]
  },
  {
    id: "history-playbook-2024-12",
    date: "2024-12-04",
    title: "History's Hidden Playbook for Investors: Lessons from Fear and Greed",
    subtitle: "Behavioral Economics Note: Recurring behavioral cycles and systemic market crises",
    company: "N/A",
    ticker: "N/A",
    exchange: "N/A",
    sector: "Macroeconomics",
    rating: "HOLD/NEUTRAL",
    type: "Thematic Note",
    format: "Article",
    conviction: "High",
    priceTarget: "N/A",
    upside: "N/A",
    link: "https://www.linkedin.com/pulse/historys-hidden-playbook-investors-lessons-from-fear-greed-mary-scott-yqifc/",
    summary: "Examining how recurring human behaviors and systemic vulnerabilities make major market crises predictable. This analysis explores how unchecked complexity and flawed regulations repeat throughout history, offering prepared investors unique contrarian opportunities by focusing on fundamental resilience.",
    tags: ["Behavioral Finance", "Market History", "Contrarian Strategy"]
  },
  {
    id: "recessions-2024-08",
    date: "2024-08-07",
    title: "The History of U.S. Recessions and What They Mean For 2025",
    subtitle: "Macroeconomic Analysis: Downturn cycles and entry points for disciplined investors",
    company: "N/A",
    ticker: "N/A",
    exchange: "N/A",
    sector: "Macroeconomics",
    rating: "HOLD/NEUTRAL",
    type: "Thematic Note",
    format: "Article",
    conviction: "High",
    priceTarget: "N/A",
    upside: "N/A",
    link: "https://www.linkedin.com/pulse/history-us-recessions-what-mean-2025-just-happened-mary-scott-sekjc/",
    summary: "Contextualizing modern market panics through the lens of historical U.S. downturns. This report highlights that while recessions vary in origin—from the Gold Standard to complex financial derivatives—they are inherently temporary, providing vital entry points for diversified, long-term investment strategies.",
    tags: ["Macroeconomics", "Recessions", "Market Cycles"]
  }
];
